### ISSUE TITLE
CLI displays uninformative version number?

### ISSUE THREAD

**Issue by kaicarver** [bitjson/s18n#9]
Even after updating to latest version via `npm install -g s18n`, the CLI `s18n -V` (btw, why not lowercase `-v`?) returns the same uninformative version number:

```
$ s18n -V
0.0.1
```

It would be more helpful if it displayed the package version, which I guess can be displayed using `npm list -g`:

```
$ npm list -g s18n
C:\Users\Kai\AppData\Roaming\npm
├─┬ gulp-l10n@1.2.1
│ └── s18n@2.0.0
└── s18n@2.0.1
```

I guess the version displayed by the CLI is the CLI's version, but that's not very useful info and does not seem to get updated:

```
bin/s18n 

7   program
8     .version('0.0.1')

package.json 

1   {
2     "name": "s18n",
3     "version": "2.0.1",
```

**Comment by bitjson** [comment]
Thanks for opening the issue! Solved in the latest release, which now includes tests for the CLI.
